language: csharp
solution: Turms.sln
mono: latest
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet test Turms.UnitTest
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - xbuild /p:Configuration=Release Turms.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Turms.AcceptanceTest/Turms.AcceptanceTest.csproj