// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code

#pragma warning disable
namespace Turms.AcceptanceTest
{
    using TechTalk.SpecFlow;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MessageCreationFeature : Xunit.IClassFixture<MessageCreationFeature.FixtureData>,
        System.IDisposable
    {
        private static TechTalk.SpecFlow.ITestRunner testRunner;

        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "MessageCreation.feature"
#line hidden

        public MessageCreationFeature(MessageCreationFeature.FixtureData fixtureData,
            Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }

        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(
                new System.Globalization.CultureInfo("en-US"), "MessageCreation",
                "\tIn order to process invalid messages\r\n\tAs an interface engineer\r\n\tI want to crea" +
                "te new HL7 messages", ProgrammingLanguage.CSharp, ((string[]) (null)));
            testRunner.OnFeatureStart(featureInfo);
        }

        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(
                _testOutputHelper);
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }

        [Xunit.FactAttribute(DisplayName = "Create a new ADT^A01 message")]
        [Xunit.TraitAttribute("FeatureTitle", "MessageCreation")]
        [Xunit.TraitAttribute("Description", "Create a new ADT^A01 message")]
        [Xunit.TraitAttribute("Category", "mytag")]
        public virtual void CreateANewADTA01Message()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(
                "Create a new ADT^A01 message", new string[]
                {
                    "mytag"
                });
#line 7
            this.ScenarioSetup(scenarioInfo);
#line 8
            testRunner.Given("I create a new message", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "Given ");
#line 9
            testRunner.And("I populate the MSH Segment", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 10
            testRunner.And("I populate the PID Segment", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "And ");
#line 11
            testRunner.When("I encode the message", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)), "When ");
#line 12
            testRunner.Then("the message can be parsed", ((string) (null)), ((TechTalk.SpecFlow.Table) (null)),
                "Then ");
#line hidden
            this.ScenarioCleanup();
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            public FixtureData()
            {
                MessageCreationFeature.FeatureSetup();
            }

            void System.IDisposable.Dispose()
            {
                MessageCreationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore

#endregion